#!/usr/bin/env pwsh
# Audit OBJ triangle counts across src/main/resources/models.
# Writes over16.txt listing any visual mesh whose raw 'f '-line count
# exceeds PerfFlags.PER_CELL_SHADOW_TRI_CAP (16).
#
# Referenced by:
#   specs/008-fps-fov-shadow-culling/quickstart.md §10
#   specs/008-fps-fov-shadow-culling/contracts/shadow-proxy-discovery.md §6
#
# Note: raw 'f '-line count is an upper bound. Actual emitted tri counts
# are lower after cullInteriorFaces (AssetLoader.kt). Cross-reference
# the shadow-emitter list in the contract before authoring proxies.

Set-Location $PSScriptRoot
$files = Get-ChildItem -Path 'src\main\resources\models' -Recurse -Filter *.obj
$rows = foreach ($f in $files) {
    $tris = 0
    foreach ($line in Get-Content -LiteralPath $f.FullName) {
        if ($line -like 'f *') { $tris++ }
    }
    [PSCustomObject]@{ Tris = $tris; Rel = $f.FullName.Substring($PWD.Path.Length + 1) }
}
$over = $rows | Where-Object { $_.Tris -gt 16 } | Sort-Object Tris -Descending
$lines = @("# Files with > 16 raw triangles (PerfFlags.PER_CELL_SHADOW_TRI_CAP)",
           "# Generated by count_tris.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')",
           "# Format: <tris>  <path>",
           "# Total: $($over.Count) over-budget OBJs",
           "")
$lines += $over | ForEach-Object { "{0,5}  {1}" -f $_.Tris, $_.Rel }
$lines | Set-Content -Path (Join-Path $PSScriptRoot 'over16.txt') -Encoding utf8
Write-Output "Wrote over16.txt: $($over.Count) files exceed 16 raw tris (of $($rows.Count) total)."

